### ISSUE TITLE
How I can deploy all project to the my shop?

### ISSUE THREAD

**Issue by Lysindr** [Pixel2HTML/shopify-skeleton#1]
Hello! Can You help us with next issue?
We have 3 gulp-tasks:
1. release - its build our theme in zip-archive. Its need for the first uploading to the shop-theme?
2. serve - starting local-server, watching the files and deploy the files which I change.
3. default - it's build our theme and run "serve".
So, do we have task like  "slate start" for **FULL** theme deployment?

**Comment by shelldandy** [comment]
Hello @Lysindr you'll need to setup some form of CI add some environmental keys and use the upload gulp task.

I can't add that task since its supposed to be different for each CI but i'll see how I can tweak the package to accept something like that

**Comment by Strelia** [comment]
Hello, please write more about CI or add example to the Readme

**Comment by shelldandy** [comment]
@Strelia there are way too many CI solutions but for example you could use the one from gitlab or travisCI, the one from bitbucket, etc

**Comment by shelldandy** [comment]
@Strelia @Lysindr i have updated the package with a new shopify upload provider and some new npm scripts

as always

```sh
$ npm install -g generator-pixel2html-shopify
```
