### ISSUE TITLE
sync-parrot-api error

### ISSUE THREAD

**Issue by cmawhorter** [Pixel2HTML/shopify-skeleton#12]
I'm getting an error while setting up a new project.  node 9.3.0

```
added 1501 packages, removed 183 packages and moved 47 packages in 57.414s
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/blah/shopify-skeleton/node_modules/sync-parrot-api/dist/default-parrot.txt'
```

My steps were:

1. `mkdir test && cd test && echo '{}' > package.json`
1. `npm i yo`
1. `npm i @pixel2html/generator-shopify`
1. `yo @pixel2html/shopify`
1. Since I created a package.json, yo complained that one already existed.  I selected overwrite.
1. yo asked if i wanted to install deps.  I said yes.  It installed deps and then failed at the end.  

Everything seemed to install so I'm guessing this was part of a final "install done" message.

**Comment by shelldandy** [comment]
Thanks for your report @cmawhorter i'll move your issue to our mono-repo now to deal with it.
