### ISSUE TITLE
Adding / Controlling order of vendor JS files

### ISSUE THREAD

**Issue by pjatx** [Pixel2HTML/shopify-skeleton#4]
Hey Guys, 

I'm not super familiar with Browserify / Babel and am having trouble adding some vendor js files and have them load in the order I'd like them to. 

Could you provide a quick example of the proper way to add a few JS files to this project and control the order of their loading? 

IE - let's assume that vendor2 depends on vendor1 and vendor3 on vendor2

* vendor1.js
* vendor2.js
* vendor3.js

Guessing it would also be possible to use npm to install them and include, but not sure how to accomplish this. If this goes beyond the support of this project, totally understand as well.

**Comment by shelldandy** [comment]
```bash
$ yarn add slick-carousel
```

```js
import $ from 'jquery'
 // slick depends on jquery
// also make sure your vendors are in UMD format
import 'slick-carousel'

$('.slider').slick()
```

That will _just work_ but if you want to split your vendors go to `gulp.config.js` and add the other vendors (with the same name as the package.json) in config.scriptVendors array

https://github.com/Pixel2HTML/shopify-skeleton/blob/master/src/app/templates/gulp/gulp.config.js#L30-L32

That would look:

```js
...
scriptVendors: [
    'jquery',
   'slick-carousel'
  ]
...
```

**Comment by shelldandy** [comment]
Also we've been testing some juicy new stuff and v2.0 will pack webpack with the vendors automatically split.

Coming in the next 2 weeks or so, we are testing it internally ATM

https://twitter.com/mpalau/status/938492082976706561

**Comment by pjatx** [comment]
@mike3run thanks! And I would be making these changes in app.js vs index.js?

**Comment by shelldandy** [comment]
app.js is the main entry point of the app browserify will transverse the app from that point you can make the changes on any file you want but in the end it has to go to app.js 

https://survivejs.com/webpack/what-is-webpack/#webpack-s-execution-process

Its a webpack blog post but its the same idea (and we'll be using webpack here in the next week or so anyways)

**Comment by pjatx** [comment]
@mike3run awesome, thanks for the hand-holding and excited for the next release
