### ISSUE TITLE
generator copy suggestion

### ISSUE THREAD

**Issue by eballeste** [Pixel2HTML/shopify-skeleton#8]
thank you for this

just wanted to suggest that you change line #208 of your generator script to say:
`this.log('PS: use npm run start to install')`

**Comment by shelldandy** [comment]
But the command is `npm run code` `npm start` is an alias but they both work

**Comment by eballeste** [comment]
@mike3run you can't run `npm run code` without first running `npm run start`

as the title said, it was just a suggestion since running `yo @pixel2html/shopify` followed by the suggestion to start with `npm run code` will default in an error.

**Comment by shelldandy** [comment]
that is true, however the installer asks if you want it to `yarn install` for you.

But the suggestion of the error is ok, we can take a PR if you're up for the challenge 😄

**Comment by eballeste** [comment]
#11

**Comment by shelldandy** [comment]
Moving this issue to the monorepo
